### ISSUE TITLE
Problems with the tutorial

### ISSUE THREAD

**Issue by mboisson** [SIMEXP/tutorials#5]
This tutorial does not follow the guidelines for transferring data : 
https://docs.computecanada.ca/wiki/Transferring_data#Rsync

Also, the modules should be loaded in the job script : 
```
module load singularity/3.4
```

**Comment by mboisson** [comment]
I'm talking about this tutorial : 
https://github.com/SIMEXP/tutorials/blob/master/HPC_use/How_to_use_compute_canada.md

by @ltetrel

**Comment by ltetrel** [comment]
Hi @mboisson thanks for your feedback,
For the guideline to transfer the data, what do you mean ?

**Comment by mboisson** [comment]
Oh, actually, I am wrong for this part. I see that you chose the second recommended option (`-ltr`) rather than `-avz --no-p --no-g`. You can ignore this part of the comment. The module should still be loaded however.

**Comment by ltetrel** [comment]
Yep I just added it thanks :)
801d5219c77d7d35e6a8fcba2e31eb292bb911e3
